name: HER2

dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - pip
  - ipykernel
  - h5py
  - pip:
    - uuid 
    - datetime
    - tslearn
    - argparse